# -*- coding: utf-8 -*-
"""Descartes_CSV_Manipulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGC679OjGsQkvC_2vB2gKF03eUNyucf0

Name: Descartes Research Lab

Author: Ayush Nigam

Action: Manipulating game data csv to add accuracy performance columns

Note:
working memory:

*   Found bug where if you click on the same tile, it counts it as an attempt.
  
* Code bug: accuracy by increment doesnt work if all the values happen to be in increment eg- 0-1-2-4-5-6 - this give 100% accuracy

#Importing libraries required
"""

import csv
import json
import pandas as pd
import numpy as np

import psycopg2
import os
import shutil





"""#Code for Working Memory"""

def working_memory_manipulation():
  #To store frequency and accuracy of blocks
  modes1 = {"Easy":[0,0],"Medium":[0,0], "Hard":[0,0]}

  cols = ["Userid",	"BlockNo",	"Difficulty",	"Start_time",	"End_time",	"Results_responses", "Results_rt", "Results_targetvalue_stim", "Results_num_stim", "Results_correct"]
  df = pd.read_csv(name, index_col=False, skiprows=1, names= cols)
  block_list = list(df["Difficulty"])
  responses_list = list(df["Results_responses"])
  num_stim_list = list(df["Results_num_stim"])

  overall_acc1 = 0


  #making the correct order response
  correct_response = list(range(0,16))
  #for accuracy acc to position
  accuracy_column = []

  #for correct answers
  correct_answers_list = []
  # To go through all the responses
  for i in range(len(responses_list)):
    count_correct = 0

    #to create a
    response = responses_list[i].split("-")
    #print(response)
    #print(correct_response)

    # going throught all the responses and comparing it to the correct response
    # order of 0-1-2-3-4-5-6-7-8-9-...
    for j in range(len(response)):
      if int(response[j]) == (correct_response[j]):
        count_correct +=1


    #calculating accuracy
    accuracy = (count_correct/num_stim_list[i])
    overall_acc1 += accuracy
    #print(count_correct, num_stim_list[i])
    accuracy_column.append(accuracy)


    if block_list[i] == "Easy":
      modes1["Easy"][0] += 1
      modes1["Easy"][1] += accuracy

    elif block_list[i] == "Medium":
      modes1["Medium"][0] += 1
      modes1["Medium"][1] += accuracy

    elif block_list[i] == "Hard":
      modes1["Hard"][0] += 1
      modes1["Hard"][1] += accuracy

    #Correct answer
    correct_answers_list.append("-".join(str(i) for i in list(range(0,num_stim_list[i]))))

  if modes1["Easy"][0] != 0:
    modes1["Easy"][1] /= modes1["Easy"][0]
  if modes1["Medium"][0] != 0:
    modes1["Medium"][1] /= modes1["Medium"][0]
  if modes1["Hard"][0] != 0:
    modes1["Hard"][1] /= modes1["Hard"][0]


  if len(accuracy_column) != 0:
    overall_acc1 /= len(accuracy_column)




  df["Correct Answer"] = correct_answers_list
  df["Accuracy"] = accuracy_column


  #Single column with individual row wise overal difficulty
  #Overall accuracy of current row's block
  overall_accuracy1 = []
  for diff in block_list:
    match(diff):
      case "Easy":
        overall_accuracy1.append(modes1["Easy"][1])
      case "Medium":
        overall_accuracy1.append(modes1["Medium"][1])
      case "Hard":
        overall_accuracy1.append(modes1["Hard"][1])

  df["Overall Accuracy for current block"] = overall_accuracy1


  #Separate Columns for each block accuracies
  easy_overall_acc_list1 = [modes1["Easy"][1]]*len(df)
  medium_overall_acc_list1 = [modes1["Medium"][1]]*len(df)
  hard_overall_acc_list1 = [modes1["Hard"][1]]*len(df)

  df["Overall Accuracy"] = [overall_acc1]*len(df)
  df["Overall Accuracy Easy block"] = easy_overall_acc_list1
  df["Overall Accuracy Medium block"] = medium_overall_acc_list1
  df["Overall Accuracy Hard block"] = hard_overall_acc_list1


  return df

"""#Code for Enumeration"""

def enumeration_manipulation():
  #To store frequency and accuracy of blocks
  modes = {"Easy":[0,0],"Medium":[0,0], "Hard":[0,0]}

  cols = ["Userid",	"Blockno", "Difficulty", "Start_time", "End_time", "Results_Responses",	"Results_rt", "Results_targetvalue"]
  df = pd.read_csv(name, index_col=False, skiprows=1, names= cols)

  block_list = list(df["Difficulty"])
  enum_responses_list = list(df["Results_Responses"])
  enum_answers_list = list(df["Results_targetvalue"])
  enum_accuracy = []

  for ans in range(len(enum_responses_list)):
    accuracy = -1
    if enum_responses_list[ans] == enum_answers_list[ans]:
      accuracy = 1
    else:
      accuracy = 0

    enum_accuracy.append(accuracy)

    if block_list[ans] == "Easy":
      modes["Easy"][0] += 1
      modes["Easy"][1] += accuracy
    elif block_list[ans] == "Medium":
      modes["Medium"][0] += 1
      modes["Medium"][1] += accuracy
    elif block_list[ans] == "Hard":
      modes["Hard"][0] += 1
      modes["Hard"][1] += accuracy

  df["Accuracy"] = enum_accuracy

  if modes["Easy"][0] != 0:
    modes["Easy"][1] /= modes["Easy"][0]
  if modes["Medium"][0] != 0:
    modes["Medium"][1] /= modes["Medium"][0]
  if modes["Hard"][0] != 0:
    modes["Hard"][1] /= modes["Hard"][0]

  sum = 0
  for i in enum_accuracy:
    if i == 1:
      sum+=1
  enum_overallAcc = sum/len(enum_accuracy)

  #Single column with individual row wise overal difficulty
  #Overall accuracy of current row's block
  overall_accuracy_block = []
  for diff in block_list:
    match(diff):
      case "Easy":
        overall_accuracy_block.append(modes["Easy"][1])
      case "Medium":
        overall_accuracy_block.append(modes["Medium"][1])
      case "Hard":
        overall_accuracy_block.append(modes["Hard"][1])

  df["Overall Accuracy for current block"] = overall_accuracy_block
  df["Overall Accuracy"] = [enum_overallAcc]*len(df)
  df["Overall Accuracy Easy block"] = [modes["Easy"][1]]*len(df)
  df["Overall Accuracy Medium block"] = [modes["Medium"][1]]*len(df)
  df["Overall Accuracy Hard block"] = [modes["Hard"][1]]*len(df)

  return df

"""#Code for Task Switch


"""

def taskswitch_manipulation():
  #To store frequency and accuracy of blocks
  modes = {"Easy":[0,0],"Medium":[0,0], "Hard":[0,0]}
  cols = ["Userid",	"Blockno",	"Difficulty",	"Start_time",	"End_time",	"Results_Responses",	"Results_rt",	"Results_ind_switch",	"Results_indtask",	"Results_trail_target"]
  df = pd.read_csv(name, index_col=False, skiprows=1, names= cols)

  ts_responses_list = list(df["Results_Responses"])
  ts_indtask_list = list(df["Results_indtask"])
  ts_target_list = list(df["Results_trail_target"])
  block_list = list(df["Difficulty"])
  
  df["End_time"] = df["End_time"].fillna("None")
  df["Results_rt"] = df["Results_rt"].fillna("None")

  #To store what the user should have inputted to be correct
  ts_correct_response_list = []
  #To store hit or miss field where 1 is a hit and 0 is a miss
  ts_hit_miss = []
  #To calculate accuracy
  ts_accuracy = []
  for ind in range(len(ts_target_list)):
    task = ts_indtask_list[ind]
    target = ts_target_list[ind]
    ans = -1
    # for odd/even task
    if task == 0:
      if target % 2 == 1:
        ans = 1
      else:
        ans = 2

    # for low/high task
    elif task == 1:
      if target < 5:
        ans = 1
      elif target > 5:
        ans = 2
    ts_correct_response_list.append(ans)

    # To calculate hits/misses
    if ts_responses_list[ind] == 0:
      ts_hit_miss.append(0)
    else:
      ts_hit_miss.append(1)

    # To calculate accuracy: 1 if accurate, 0 if not.
    accuracy = -1
    if ts_responses_list[ind] == ans:
      accuracy = 1
    else:
      accuracy = 0
    ts_accuracy.append(accuracy)

    if block_list[ind] == "Easy":
      modes["Easy"][0] += 1
      modes["Easy"][1] += accuracy
    elif block_list[ind] == "Medium":
      modes["Medium"][0] += 1
      modes["Medium"][1] += accuracy
    elif block_list[ind] == "Hard":
      modes["Hard"][0] += 1
      modes["Hard"][1] += accuracy

  df["Correct action"] = ts_correct_response_list
  df["Hit/Miss"] = ts_hit_miss
  df["Accuracy"] = ts_accuracy

  if modes["Easy"][0] != 0:
    modes["Easy"][1] /= modes["Easy"][0]
  if modes["Medium"][0] != 0:
    modes["Medium"][1] /= modes["Medium"][0]
  if modes["Hard"][0] != 0:
    modes["Hard"][1] /= modes["Hard"][0]

  #Single column with individual row wise overal difficulty
  #Overall accuracy of current row's block
  overall_accuracy_block = []
  for diff in block_list:
    match(diff):
      case "Easy":
        overall_accuracy_block.append(modes["Easy"][1])
      case "Medium":
        overall_accuracy_block.append(modes["Medium"][1])
      case "Hard":
        overall_accuracy_block.append(modes["Hard"][1])
  ts_overall_acc = sum(ts_accuracy)/len(ts_accuracy)
  df["Overall Accuracy for current block"] = overall_accuracy_block
  df["Overall Accuracy"] = [ts_overall_acc]*len(df)
  df["Overall Accuracy Easy block"] = [modes["Easy"][1]]*len(df)
  df["Overall Accuracy Medium block"] = [modes["Medium"][1]]*len(df)
  df["Overall Accuracy Hard block"] = [modes["Hard"][1]]*len(df)

  return df




DATABASE = {
    'dbname': 'cognitive_battery',
    'user': 'postgres',
    'password': 'postgres',
    'host': '10.10.1.2',
    'port': '5432'
}




DATA_DIR = 'C:\\Users\\brook\\Downloads\\'
CURRENT_DIR = os.getcwd()
SAVE_DATA_DIR = CURRENT_DIR + '\..\..\GameData'
if not os.path.exists(SAVE_DATA_DIR):
    os.makedirs(SAVE_DATA_DIR)


list_file = []
list_file_save = []
for file in os.listdir(DATA_DIR):
    file_path = os.path.abspath(os.path.join(DATA_DIR,file))
    file_save_path = os.path.abspath(os.path.join(SAVE_DATA_DIR,file))
    if ('enumeration' in file_path) or ('workingmemory' in file_path) or ('switch' in file_path):
        list_file.append(file_path)
        list_file_save.append(file_save_path)

    
conn = psycopg2.connect(**DATABASE)

for index,name in enumerate(list_file):
    print(name)
    game_name = name
    cursor = conn.cursor()
    """#Uploading csv file"""

    which_game = 0
    # working memory - 1
    # enumeration - 2
    # task switching - 3
    if "workingmemory" in game_name:
      which_game = 1
    elif "enumeration" in game_name:
      which_game = 2
    elif "taskswitch" in game_name or "switch" in game_name:
      which_game = 3


    """#To decide what type of file  to work on"""

    if which_game == 1:
      df = working_memory_manipulation()
      name_new = "workingmemory_manipulated.csv"
    elif which_game == 2:
      df = enumeration_manipulation()
      name_new = "enumeration_manipulated.csv"
    elif which_game == 3:
      df = taskswitch_manipulation()
      name_new = "taskswitch_manipulated.csv"
      
      
    #file_path = temp_file_path + name_new

    #user_id = filename[:4]  # Extract the first four characters from the filename as the user ID
    #data_dict = {'user_id': user_id}  # Initialize a dictionary with user ID

    #df = pd.read_csv(file_path)
    data_dict = df.to_dict(orient = 'list')

    user_id = data_dict['Userid'][0]

    if which_game == 1:
      df = working_memory_manipulation()
      name_new = "workingmemory_manipulated.csv"
      
      data_dict['Task_type'] = 'working memory'
      data_dict['Accuracy_Easy']=data_dict['Overall Accuracy Easy block'][0]
      data_dict['Accuracy_Medium']=data_dict['Overall Accuracy Medium block'][0]
      data_dict['Accuracy_Hard']=data_dict['Overall Accuracy Hard block'][0]
      data_dict['Accuracy_Overall']=data_dict['Overall Accuracy'][0]
      
      del(data_dict['Overall Accuracy Easy block'])
      del(data_dict['Overall Accuracy Medium block'])
      del(data_dict['Overall Accuracy Hard block'])
      del(data_dict['Overall Accuracy for current block'])
      del(data_dict['Userid'])
      del(data_dict['Overall Accuracy'])
      
      json_data = json.dumps(data_dict)
      # Print the JSON data
      cursor.execute("""INSERT INTO working_memory (userid,data)VALUES (%s, %s);""", (user_id,json_data))
      shutil.move(game_name, list_file_save[index])
      print("written to database")
      
    elif which_game == 2:
      df = enumeration_manipulation()
      name_new = "enumeration_manipulated.csv"
      
      data_dict['Task_type'] = 'Enumeration'
      data_dict['Accuracy_Easy']=data_dict['Overall Accuracy Easy block'][0]
      data_dict['Accuracy_Medium']=data_dict['Overall Accuracy Medium block'][0]
      data_dict['Accuracy_Hard']=data_dict['Overall Accuracy Hard block'][0]
      data_dict['Accuracy_Overall']=data_dict['Overall Accuracy'][0]
      
      del(data_dict['Overall Accuracy Easy block'])
      del(data_dict['Overall Accuracy Medium block'])
      del(data_dict['Overall Accuracy Hard block'])
      del(data_dict['Overall Accuracy for current block'])
      del(data_dict['Userid'])
      del(data_dict['Overall Accuracy'])
      
      json_data = json.dumps(data_dict)
      # Print the JSON data
      cursor.execute("""INSERT INTO enumeration (userid,data)VALUES (%s, %s);""", (user_id,json_data))
      shutil.move(game_name, list_file_save[index])
      print("written to database")
      
    elif which_game == 3:
      df = taskswitch_manipulation()
      name_new = "taskswitch_manipulated.csv"
      
      data_dict['Task_type'] = 'task switch'
      data_dict['Accuracy_Easy']=data_dict['Overall Accuracy Easy block'][0]
      data_dict['Accuracy_Medium']=data_dict['Overall Accuracy Medium block'][0]
      data_dict['Accuracy_Hard']=data_dict['Overall Accuracy Hard block'][0]
      data_dict['Accuracy_Overall']=data_dict['Overall Accuracy'][0]
      
      del(data_dict['Overall Accuracy Easy block'])
      del(data_dict['Overall Accuracy Medium block'])
      del(data_dict['Overall Accuracy Hard block'])
      del(data_dict['Overall Accuracy for current block'])
      del(data_dict['Userid'])
      del(data_dict['Overall Accuracy'])
      
      json_data = json.dumps(data_dict)
      # Print the JSON data
      cursor.execute("""INSERT INTO task_switching (userid,data)VALUES (%s, %s);""", (user_id,json_data))
      shutil.move(game_name, list_file_save[index])
      print("written to database")
      
      



    conn.commit()
    cursor.close()
conn.close()

